PREFIX ex: <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?album rdf:type ex:Album .
  ?album ex:name ?name .
  ?album ex:date ?date .
  ?album ex:artist ex:The_Beatles .
}
WHERE {
  ?album rdf:type ex:Album .
  ?album ex:artist ex:The_Beatles .
  ?album ex:name ?name .
  ?album ex:date ?date .
}

