name: Continuous Integration process
run-name: ${{ github.actor }} has launched CI process on ${{ github.ref_name }}
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Continuous-Integration-Actions:
    runs-on: self-hosted

    env:
      PACKAGE_TOKEN: ${{ secrets.JLS_TOKEN }}

    steps:
      - name: Checkout sources
        id: ci-sources-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        id: ci-java-setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.12-venv python3-pip || true
          python3 -m pip install --user --upgrade pip || true

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        id: ci-gradle-build
        run: ./gradlew clean assemble

      - name: Gradle tests
        run: ./gradlew test

      - name: Generate JaCoCo Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.0
        with:
          paths: |
            **/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          update-comment: true

      - name: Display Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: 'build/test-results/**/*.xml'
          reporter: java-junit

      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Final Step
        id: ci-final-step
        run: |
          echo "This job's status is ${{ job.status }}."
          echo "Created jar file(s):"
          find ./build -name '*.jar'
